/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Top: typeof import('./src/components/Top.vue')['default']
    WelcomHome: typeof import('./src/components/WelcomHome.vue')['default']
  }
}
